{{- if and .Values.minio.enabled .Values.minioJob.enabled .Values.minioJob.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mlflow-multitenant.minioJob.fullname" . }}
  labels:
    {{- include "mlflow-multitenant.labels" . | nindent 4 }}
    app.kubernetes.io/component: configure-minio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mlflow-multitenant.minioJob.fullname" . }}
subjects:
- apiGroup: ''
  kind: ServiceAccount
  name: {{ include "mlflow-multitenant.minioJob.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
