{{- if and .Values.minio.enabled .Values.minioJob.enabled .Values.minioJob.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow-multitenant.minioJob.serviceAccountName" . }}
  labels:
    {{- include "mlflow-multitenant.labels" . | nindent 4 }}
    app.kubernetes.io/component: configure-minio
  {{- with .Values.minioJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
