mlflow:
  tenants:
  - id: tenant-1
    valuesTemplate: |
      image:
        tag: {{ include "mlflow-multitenant.fullname" . }}
  - id: tenant-2
    values:
      resources:
        requests:
          cpu: 4
  - id: tenant-3
    values:
      ingress:
        enabled: true
        className: something
    valuesTemplate: |
      ingress:
        hosts:
        {{- range list "a" "b" "c" }}
        - host: {{ . }}
          paths:
          - path: /
            pathType: Prefix
        {{- end }}
