{{- define "mlflow-oidc-proxy.configMapContents" -}}
data:
  '{{ .Values.config.existingConfigMap.key }}': |-
    {{- $dot := . }}
    {{- $output := include "mlflow-oidc-proxy.robots" . | fromJson }}
    {{- $robots := ($output | fromJson).robots }}
    {{ $output | toYaml | fail }}
    {{- $config := deepCopy .Values.config.yaml }}
    {{- $config = set $config "robots" (set $config.robots "robots" $robots) }}
    {{- $config | toYaml | nindent 4 }}
{{- end -}}

{{- if not .Values.config.existingConfigMap.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow-oidc-proxy.configMapName" . }}
  labels:
    {{ include "mlflow-oidc-proxy.labels" . | nindent 4 }}
{{ include "mlflow-oidc-proxy.configMapContents" . }}
{{- end }}
