{{- define "mlflow-oidc-proxy.secretContents" -}}
stringData:
  '{{ .Values.credentials.existingSecret.usernameKey }}': '{{ .Values.credentials.username }}'
  '{{ .Values.credentials.existingSecret.passwordKey }}': '{{ .Values.credentials.password }}'
{{- end -}}

{{- if not .Values.credentials.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow-oidc-proxy.secretName" . }}
  labels:
    {{ include "mlflow-oidc-proxy.labels" . | nindent 4 }}
{{ include "mlflow-oidc-proxy.secretContents" . }}
{{- end }}
