apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow.fullname" . }}
data:
  {{- include "mlflow.configMapData" . | nindent 2 }}

{{- define "mlflow.configMapData" -}}
docker-entrypoint.sh: |
  #!/bin/bash -xeu
  pip install -r /var/run/requirements.txt
  exec mlflow server --host '0.0.0.0' --port '5000' "$@"
requirements.txt: |
  {{- range $name, $version := .Values.requirements }}
  {{ $name }}{{ $version | default "" }}
  {{- end }}
{{- end -}}
