apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentinel
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dummy
            port:
              number: 80

