{{/*
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "notebook-job.fullname" . }}
  labels:
    {{- include "notebook-job.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 8Gi
*/}}
