{{- if .Values.mlflow.values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow-multitenant.serviceAccountName" . }}
  labels:
    {{- include "mlflow-multitenant.labels" . | nindent 4 }}
  {{- with .Values.mlflow.values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
