{{- if and .Values.keycloak.enabled .Values.keycloakJob.enabled .Values.keycloakJob.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow-multitenant.keycloakJob.serviceAccountName" . }}
  labels:
    {{- include "mlflow-multitenant.labels" . | nindent 4 }}
    app.kubernetes.io/component: configure-keycloak
  {{- with .Values.keycloakJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
